### ISSUE TITLE
Add pause button

### ISSUE THREAD

**Issue by stuthedew** [luktinghin/simtiva#19]
Awesome project. Thank you so much for putting this together. Did have a few minor suggestions.

Can you add a pause button? This would be helpful if you had to step away for a second, but wanted to come back to a simulation.

**Comment by luktinghin** [comment]
Thanks for the idea. Good suggestion. I may need to think how to make it clear to the user in that case because "pause simulation" (run time is stopped, all infusion states frozen in time) vs. "pause infusion" (sim continues, infusion rate is zeroed / target is zeroed) are different and I will need to think of a clear way to present it to the user

**Comment by stuthedew** [comment]
You really have done an awesome job. The website is amazing! Have you seen the program “Gasman” http://gasmanweb.com/? It’s a free software/web app that does something similar for inhalation anesthetic. They have that functionality which is what made me think of it. They also allow you to set a target “bookmark” (e.g. MAC/anesthetic depth goal, elapsed time, etc.), so you can run the sim at like 60x and then have it auto-pause when it reaches there if you want to see how long it took, or if you want to make an adjustment to your inhalation anesthetic amount or circuit flows etc. when you reach the target. It also lets you jump back to a bookmark, to redo just certain parts of your anesthetic. So if you have the induction figured out, but want to try different wake-up’s, you can just restart from the wake-up bookmark, and just redo that portion of the simulation without starting from scratch every time. Maybe there is something in there that would be useful?

Also, I’m sure in your abundant free time, if you ever want to make a combined inhalation/TIVA master simulator, that would be amazing :-)

I wish I could be more helpful actually implementing this. I do program, but more python and C++ (Arduino, circuit python, etc.). Never really learned coding for the web...

**Comment by luktinghin** [comment]
Hi, the latest update of SimTIVA allows resetting the infusion while keeping patient data, pausing of sim, and jumping back and forward in time.

Thanks for your idea and contribution!
