### ISSUE TITLE
Eleveld Propofol with and without opioid

### ISSUE THREAD

**Issue by David8L** [luktinghin/simtiva#22]
Dr Luk, your app was showcased by Dr M Irwin recently at the WCA 2024 in Singapore, and was well received.
Quite a few questions regarding Eleveld with and without opioid. What do you think about adding Eleveld without opioid in SimTIVA?
The only variables that needs to be changed are v3 (which is already programmed in your app with the opioid = 1 line,
and cl1, which just needs another if opioid = 1 check in your code. If opioid = 0 then just remove the Math.exp(-0.0138*age) reference in cl1.
Do you think this is a good idea? Do you want me to submit a pull request or will you add it in your next update? Thanks.

**Comment by luktinghin** [comment]
Hi David, very nice to hear from you. It was brilliant to hear that Prof Irwin used simtiva in his talk, although I wish I could have attended WCA. 
This idea (having the "eleveld without opioid") is good. Let me update it in the next release.

Thanks very much David and hope u are well

**Comment by luktinghin** [comment]
Dear David, good morning.
I have updated the app and included the Eleveld without opioid model. User has to select "yes" or "no" to concomitant opioid in the initial screen. Formulas and code changes are as you have suggested. 
I have made additional revisions to maintain backward compatibility and to store this info (yes/no opioid) as part of the share/save function. (Simtiva automatically saves the simulations and user can load simulations on device).
Thanks very much for the suggestion and your continuous feedback.

**Comment by luktinghin** [comment]
I have validated this new model comparing the infusion data with iTIVA and tivatrainer and found them to be almost the same. 
I am a bit surprised to know that eleveld with, and without opioid, generates quite different infusion schemes!

**Comment by David8L** [comment]
Thank you. Yes, it looks good, the calcs look correct. Yes Eleveld without opioid increases infusion rates / cumulative dose by approx 15-20% generally.
